#
# Docker file for ChRIS store development server
#
# Build with
#
#   docker build -t <name>:<tag> -f <dockerfile> .
#
# For example if building a local version, you could do:
#
#   docker build -t local/chris_store:dev -f Dockerfile_dev .
#
# In the case of a proxy (located at proxy.tch.harvard.edu:3128), do:
#
#   docker build --build-arg http_proxy=http://proxy.tch.harvard.edu:3128 --build-arg UID=$UID -t local/chris_store:dev -f Dockerfile_dev .
#
# To run an interactive shell inside this container, do:
#
#   docker run -ti --entrypoint /bin/bash local/chris_store:dev
#

FROM fnndsc/ubuntu-python3:ubuntu20.04-python3.8.5
MAINTAINER fnndsc "dev@babymri.org"

# Pass a UID on build command line (see above) to set internal UID
ARG UID=1001
ENV UID=$UID DEBIAN_FRONTEND=noninteractive VERSION="0.1"

ENV APPROOT="/home/localuser/store_backend" REQPATH="/usr/src/requirements"
COPY ["./requirements", "${REQPATH}"]
COPY ["./docker-entrypoint.sh", "/usr/src"]

RUN apt-get update                                               \
  && apt-get install -y locales                                  \
  && export LANGUAGE=en_US.UTF-8                                 \
  && export LANG=en_US.UTF-8                                     \
  && export LC_ALL=en_US.UTF-8                                   \
  && locale-gen en_US.UTF-8                                      \
  && dpkg-reconfigure locales                                    \
  && apt-get install sudo                                         \
  && apt-get install -y libssl-dev libmysqlclient-dev             \
  && apt-get install -y apache2 apache2-dev                      \
  && pip install --upgrade pip                                    \
  && pip install -r ${REQPATH}/local.txt                          \
  && useradd -l -u $UID -ms /bin/bash localuser                      \
  && echo "localuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Start as user localuser
USER localuser

WORKDIR $APPROOT
ENTRYPOINT ["/usr/src/docker-entrypoint.sh"]
EXPOSE 8010

# Start ChRIS store development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8010"]
