# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-07-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_auto_20180503_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='icon',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
