# Generated by Django 2.0.7 on 2018-08-02 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plugins', '0003_plugin_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='owner',
        ),
        migrations.AddField(
            model_name='plugin',
            name='owner',
            field=models.ManyToManyField(related_name='plugin', to=settings.AUTH_USER_MODEL),
        ),
    ]
