# Generated by Django 2.1.4 on 2019-03-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_auto_20190211_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='version',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('name', 'version')},
        ),
    ]
