# Generated by Django 2.1.4 on 2019-05-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_auto_20190308_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultStringParameter',
            new_name='DefaultStrParameter',
        ),
    ]
