# Generated by Django 2.1.4 on 2020-02-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0009_auto_20200212_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultstrparameter',
            name='value',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
