# Generated by Django 2.2.12 on 2020-11-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0013_auto_20200811_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
