# Generated by Django 2.2.12 on 2020-12-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0014_auto_20201130_1253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plugin',
            unique_together={('meta', 'dock_image'), ('meta', 'version')},
        ),
    ]
