# Generated by Django 2.2.12 on 2021-01-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0015_auto_20201207_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pluginmeta',
            name='type',
            field=models.CharField(choices=[('ds', 'Data plugin'), ('fs', 'Filesystem plugin'), ('ts', 'Topology plugin')], default='ds', max_length=4),
        ),
    ]
