# Generated by Django 2.2.24 on 2022-06-29 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0017_auto_20210916_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plugin',
            name='descriptor_file',
        ),
    ]
